In [10]:
import mysql.connector
conn=mysql.connector.connect(user='root',password='Snehal@1234',host='localhost',database='project1')
qur='create table student4(name varchar(20),mobno Varchar(20),dept varchar(20),emailid varchar(40))'
mycur=conn.cursor()
mycur.execute(qur)
mycur.close()
conn.close()

ProgrammingError: 1050 (42S01): Table 'student4' already exists

In [11]:
import mysql.connector
from tkinter import *
from tkinter import messagebox
from tkinter import ttk
win=Tk()
win.title('STUDENT MANAGEMENT SYSTEM')
win.minsize(width=800,height=600)
win.configure(bg='skyblue')

def show():
    treev.delete(*treev.get_children())
    conn=mysql.connector.connect(user='root',password='Snehal@1234',host='localhost',database='project1')
    qur='select * from stu_pro'
    mycur=conn.cursor()
    mycur.execute(qur)
    result=mycur.fetchall()
    for i in result:
        treev.insert("",'end',values=(i[0],i[1],i[2],i[3]))
    mycur.close()
    conn.close()
    
    
    
    
    
    
    
    
    

def add():
    name=n1.get()
    mobno=m1.get()
    dept=d1.get()
    emailid=em1.get()
    if (name=='' or mobno=='' or dept=='' or emailid==''):
        messagebox.showinfo('info','You have to fill all the fields')
    else:
        conn=mysql.connector.connect(user='root',password='Snehal@1234',host='localhost',database='project1')
        qur='INSERT INTO student4(name,mobno,dept,emailid) VALUES("%s","%s","%s","%s")'%(name,mobno,dept,emailid)
        mycur=conn.cursor()
        mycur.execute(qur)
        conn.commit()
        mycur.close()
        conn.close()
        messagebox.showinfo('info','info is added')
        n1.set('')
        m1.set('')
        d1.set('')
        em1.set('')
        
        
    


def result():
    root=Tk()
    root.title('Result')
    root.minsize(width=800,height=600)
    def disp():
        name=e7.get()
        if (name==''):
            messagebox.showinfo('info','You have to fill all the fields')
        else:
            conn=mysql.connector.connect(user='root',password='Snehal@1234',host='localhost',database='project1')
            qur='select mobno from student4 where name="%s"'%(name)
            mycur=conn.cursor()
            mycur.execute(qur)
            result=mycur.fetchone()
            l8.config(text=result[0]+'%')
            
    
        
    l7=Label(root,text='Student Name',width=20,bd=5,relief='ridge')
    l7.place(x=100,y=80)
    r1=StringVar()
    e7=Entry(root,width=40,bd=5,relief='ridge',textvariable=r1)
    e7.place(x=250,y=80)
    
    b7=Button(root,text='SHOW RESULT',width=20,command=disp).place(x=200,y=120)
    
    l8=Label(root,text='Marks are here',bd=5,relief='ridge',width=40)
    l8.place(x=100,y=160)
    
    root.mainloop()

def delete():
    deldata=tt.get()
    if (deldata==''):
        messagebox.showinfo('info','You have to fill all the fields')
    else:
        conn=mysql.connector.connect(user='root',password='Snehal@1234',host='localhost',database='project1')
        qur='DELETE FROM student4 WHERE name="%s"'%(deldata)
        mycur=conn.cursor()
        mycur.execute(qur)
        conn.commit()
        mycur.close()
        conn.close()
        messagebox.showinfo('info','info is deleted')
        tt.set('')

In [12]:
def update():
    name=n1.get()
    mobno=m1.get()
    dept=d1.get()
    emailid=em1.get()
    if (name=='' or mobno=='' or dept=='' or emailid==''):
        messagebox.showinfo('info','You have to fill all the fields')
    else:
        conn=mysql.connector.connect(user='root',password='Snehal@123',host='localhost',database='project1')
        qur='UPDATE student4 SET mobno="%s",dept="%s",emailid="%s" WHERE name="%s"'%(mobno,dept,emailid,name)
        mycur=conn.cursor()
        mycur.execute(qur)
        conn.commit()
        mycur.close()
        conn.close()
        messagebox.showinfo('info','info is updated')
        n1.set('')
        m1.set('')
        d1.set('')
        em1.set('')
        
    
    
    
    
    
    
    
    
    
    
    

def select():
    up=updata.get()
    if (up==''):
        messagebox.showinfo('info','You have to fill all the fields')
    else:
        conn=mysql.connector.connect(user='root',password='Snehal@1234',host='localhost',database='project1')
        qur='select * from student4 where name="%s"'%(up)
        mycur=conn.cursor()
        mycur.execute(qur)
        result=mycur.fetchall()
        for i in result:
            e1.insert(0,i[0])
            e2.insert(0,i[1])
            e3.insert(0,i[2])
            e4.insert(0,i[3]) 
        mycur.close()
        conn.close()
        updata.set('')
    
    
    
    
    
    
    
    

def clear():
    treev.delete(*treev.get_children())



#main label
lbl=Label(win,text='STUDENT MANAGEMENT SYSTEM',bd=5,relief='ridge',
          bg='white',fg='black',font=('times new roman',16,'bold'))
lbl.place(x=268,y=40)

# name label and entry
l1=Label(win,text='NAME',bd=5,width=20,relief='ridge',
          bg='white',fg='black',font=('times new roman',12,'bold'))
l1.place(x=190,y=100)

n1=StringVar()
e1=Entry(win,bd=5,width=40,relief='ridge',textvariable=n1,bg='white',
         fg='black',font=('times new roman',12,'bold'))
e1.place(x=385,y=100)

# mob no label and entry
l2=Label(win,text='MOBILE NUMBER',bd=5,width=20,relief='ridge',
          bg='white',fg='black',font=('times new roman',12,'bold'))
l2.place(x=190,y=140)

m1=StringVar()
e2=Entry(win,bd=5,width=40,relief='ridge',textvariable=m1,bg='white',
         fg='black',font=('times new roman',12,'bold'))
e2.place(x=385,y=140)

#  dept entry and label
l3=Label(win,text='DEPARTMENT',bd=5,width=20,relief='ridge',
          bg='white',fg='black',font=('times new roman',12,'bold'))
l3.place(x=190,y=180)

d1=StringVar()
e3=Entry(win,bd=5,width=40,relief='ridge',textvariable=d1,bg='white',
         fg='black',font=('times new roman',12,'bold'))
e3.place(x=385,y=180)

# email id label and entry
l4=Label(win,text='EMAIL ID',bd=5,width=20,relief='ridge',
          bg='white',fg='black',font=('times new roman',12,'bold'))
l4.place(x=190,y=220)

em1=StringVar()
e4=Entry(win,bd=5,width=40,relief='ridge',textvariable=em1,bg='white',
         fg='black',font=('times new roman',12,'bold'))
e4.place(x=385,y=220)

# button
showbtn=Button(win,text='SHOW',width=20,command=show).place(x=200,y=320)
addbtn=Button(win,text='ADD',width=20,command=add).place(x=500,y=320)
exitbtn=Button(win,text='EXIT',width=20,command=win.destroy).place(x=200,y=360)
relbtn=Button(win,text='RESULT',width=20,command=result).place(x=500,y=360)

# delete label entry button
l5=Label(win,text='Delete by Name >>',width=20,relief='ridge',bd=5,fg='black',
         bg='white',font=('times new roman',10,'bold'))
l5.place(x=190,y=400)
tt=StringVar()
e5=Entry(win,bg='white',fg='black',width=40,bd=5,textvariable=tt,font=('times new roman',12))
e5.place(x=385,y=400)
delbtn=Button(win,text='Delete',width=20,command=delete).place(x=300,y=440)

# update ...label entry select and update button
l6=Label(win,text='Update by Name >>',width=20,
           relief='ridge',bd=5,fg='black',bg='white',
           font=('times new roman',10,'bold'))
l6.place(x=190,y=500)
updata=StringVar()
e6=Entry(win,bg='white',fg='black',width=40,bd=5,
           textvariable=updata,font=('times new roman',12))
e6.place(x=385,y=500)

upbtn=Button(win,text='Update',width=20,command=update).place(x=450,y=540)
selbtn=Button(win,text='Select',width=20,command=select).place(x=300,y=540)

# tree view
treev=ttk.Treeview(win,selectmode ='browse',height=20)
treev.place(x=900,y=100,width=450)

treev["columns"] = ("1", "2", "3","4")
treev['show'] = 'headings'

treev.column("1", width = 90, anchor ='c')
treev.column("2", width = 90, anchor ='se')
treev.column("3", width = 90, anchor ='se')
treev.column("4", width = 90, anchor ='se')

treev.heading("1", text ="Name")
treev.heading("2", text ="Mobile No")
treev.heading("3", text ="Dept")
treev.heading("4", text ="EmailID")

# clear button
cleartbtn=Button(win,text=' Clear',width=20,command=clear).place(x=1080,y=560)

win.mainloop()